apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-cred-helper
  namespace: test
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-cred-helper
          containers:
          - command:
            - /bin/sh
            - -c
            - |-
              TOKEN=`aws ecr get-login --region ${AWS_DEFAULT_REGION} --registry-ids ${ACCOUNT} | cut -d' ' -f6`
              echo "ENV variables setup done."
              kubectl delete secret --ignore-not-found $SECRET_NAME
              kubectl create secret docker-registry $SECRET_NAME \
              --docker-server=https://${ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com \
              --docker-username=AWS \
              --docker-password="${TOKEN}" 
              echo "Secret created by name. $SECRET_NAME"
              echo "Secret was successfully updated at $(date)"
            envFrom:
            - secretRef:
                name: ecr-creds
            image: odaniait/aws-kubectl:latest
            name: ecr-cred-helper
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: Default
          hostNetwork: true
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecr-cred-helper
subjects:
  - kind: ServiceAccount
    name: ecr-cred-helper
    namespace: test
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: ecr-cred-helper
 namespace: test

